Update b2 jamfiles

diff --git a/jamroot b/jamroot
--- a/jamroot
+++ b/jamroot
@@ -9,7 +9,134 @@
 
 echo "Build cpp-programs ..." ;
 
+######################################################################
+
+path-constant config-file : ./project-config.jam ;
+
+import path ;
+import option ;
+
+######################################################################
+
+rule show-help ( )
+{
+	echo "--------------------------------------------------------------------------------" ;
+	echo "Help Menu:" ;
+	echo ;
+	echo "b2 help                     - show this help menu" ;
+	echo "b2 cleanall                 - Remove all temporary generated files" ;
+	echo "b2 config [config options]  - Write config to project-config.jam" ;
+	echo "b2 [build options]          - Start Build" ;
+	echo ;
+	echo "config options:" ;
+	echo "===============" ;
+	echo ;
+	echo "   --incdir=/inc/dir        - Change user-defined include dir" ;
+	echo "                              (st. botan-3 will be searched in /inc/dir/botan-3)" ;
+	echo "                              (default: /usr/include)" ;
+	echo "--------------------------------------------------------------------------------" ;
+}
+
+if [ MATCH ^(help)$ : [ modules.peek : ARGV ] ]
+{
+	show-help ;
+	echo "debug - help" ;
+	exit ;
+}
+
+if [ MATCH ^(cleanall)$ : [ modules.peek : ARGV ] ]
+{
+	echo "cleanall ..." ;
+
+	cmd = "rm -rf `find . -name bin`" ;
+	echo "$(cmd)" ;
+	SHELL $(cmd) ;
+
+	cmd = "rm -rf $(config-file)" ;
+	echo "$(cmd)" ;
+	SHELL $(cmd) ;
+
+	echo "debug - cleanall" ;
+
+	exit ;
+}
+
+if [ MATCH ^(config)$ : [ modules.peek : ARGV ] ]
+{
+	SHELL ": > $(config-file)" ;
+
+	incdir = [ option.get incdir ] ;
+	if ! $(incdir)
+	{
+		incdir = /usr/include ;
+	}
+	SHELL "echo \"constant incdir : $(incdir) ;\" >> $(config-file)" ;
+
+	echo "Your config:" ;
+	echo "============" ;
+	echo "incdir\t\t$(incdir)" ;
+	echo "============" ;
+	echo "debug - config" ;
+	exit ;
+}
+
+if ! [ path.exists $(config-file) ]
+{
+	show-help ;
+	echo "debug - exists" ;
+	exit ;
+}
+
+######################################################################
+# botan-3
+
+project
+:
+	default-build
+		<cxxstd>23
+;
+
 alias boost-headers ;
 
+
+######################################################################
+#|
+	check botan-3: it must exist at $(incdir)
+|#
+
+echo ;
+if ! [ path.exists $(incdir)/botan-3 ]
+{
+	echo "ERROR:" ;
+	echo "\t$(incdir)/botan-3 does not exist," ;
+	echo "Fix:" ;
+	echo "\tchange b2 config --incdir=your/path/to/include to contain botan-3" ;
+	exit ;
+}
+else if ! [ path.exists $(incdir)/botan-3/botan/asio_stream.h ]
+{
+	echo "ERROR:" ;
+	echo "\t$(incdir)/botan-3 does exist," ;
+	echo "\tbut $(incdir)/botan-3/botan/asio_stream.h does not exist," ;
+	echo "\thave you built botan-3 with boost support?" ;
+	echo "Fix:" ;
+	echo "\tRebuild botan-3 with boost support." ;
+	exit ;
+}
+echo "Found: $(incdir)/botan-3/botan/asio_stream.h" ;
+
+lib
+	botan-3
+:
+:
+	<name>botan-3
+:
+:
+	<include>$(incdir)/botan-3
+;
+######################################################################
+
 build-project src ;
+
+######################################################################
 
